name: book_manager
description: Uma CLI que consome a API do Google Books, gerencia uma biblioteca pessoal e sincroniza dados localmente..
version: 1.0.0
# repository: https://github.com/sousxa/book_manager

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

# dart pub global activate --source path (Resolver isso depois)
executables: 
  main: book_manager
